# See http://msdn.microsoft.com/en-us/library/ms164311.aspx for
# command-line options to MSBuild.

# Speeding up a Visual Studio build.
# http://blogs.msdn.com/b/vcblog/archive/2011/01/05/damn-my-vc-project-is-building-slower-in-vs2010-what-do-i-do-now-a-step-by-step-guide.aspx
version: 'build_{build}-{branch}'

image:
  - Visual Studio 2015

platform: x86

build:
  parallel: true

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 2015"
      BUILDFLAGS: "/verbosity:normal"
    - GENERATOR: "MinGW Makefiles"
      BUILDFLAGS: "VERBOSE=1"

init:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=C:\MinGW\bin;%PATH%
  - mkdir C:\Software

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake --version

build_script:
  - cmake -H. -Bbuild -G"%GENERATOR%" -DCMAKE_INSTALL_PREFIX=C:\Software\message
  - if %GENERATOR%=="Visual Studio 14 2015" (cmake --build build --target help.vcxproj) else (cmake --build build --target help)
  - if %GENERATOR%=="Visual Studio 14 2015" (cmake --build build --target install.vcxproj -- %BUILDFLAGS%) else (cmake --build build --target install -- %BUILDFLAGS%)
  - if %GENERATOR%=="Visual Studio 14 2015" (cmake --build build --target package_source.vcxproj -- %BUILDFLAGS%) else (cmake --build build --target package_source %BUILDFLAGS%)
  - if %GENERATOR%=="Visual Studio 14 2015" (cmake --build build --target package.vcxproj -- %BUILDFLAGS%) else (cmake --build build --target package %BUILDFLAGS%)

deploy: off
