# See http://msdn.microsoft.com/en-us/library/ms164311.aspx for
# command-line options to MSBuild.

# Speeding up a Visual Studio build.
# http://blogs.msdn.com/b/vcblog/archive/2011/01/05/damn-my-vc-project-is-building-slower-in-vs2010-what-do-i-do-now-a-step-by-step-guide.aspx
version: 'build_{build}-{branch}'

platform: x86

build:
  parallel: true

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      GENERATOR: "MinGW Makefiles"
      BUILDFLAGS: "VERBOSE=1"
    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      GENERATOR: "Unix Makefiles"
      BUILDFLAGS: "VERBOSE=1"
    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      GENERATOR: "MSYS Makefiles"
      BUILDFLAGS: "VERBOSE=1"
    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      GENERATOR: "Ninja"
      BUILDFLAGS: "-v"
    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      GENERATOR: "Visual Studio 14 2015"
      BUILDFLAGS: "/verbosity:normal"

init:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - dir C:\cygwin64
  - dir C:\msys64
  - set PATH=C:\MinGW\bin;%PATH%
  - set PATH=C:\cygwin64;%PATH%
  - set PATH=C:\msys64;%PATH%
  - mkdir C:\projects\software
  - mkdir C:\projects\deps

install:
  # Install GFortran
  - mingw-get install fortran
  # Install dependencies in C:\projects\deps
  - cd C:\projects\deps
  # Install Kitware-maintained Ninja
  - set NINJA_URL="https://github.com/Kitware/ninja/releases/download/v1.7.2.gaad58.kitware.dyndep-1/ninja-1.7.2.gaad58.kitware.dyndep-1_i686-pc-windows-msvc.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z e ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=%PATH%;C:\projects\deps\ninja

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake --version

build_script:
  - cmake -H. -Bbuild -G"%GENERATOR%" -DCMAKE_INSTALL_PREFIX=C:\projects\software\message
  - IF "%GENERATOR%"=="Visual Studio 14 2015" (
    cmake --build build --target HELP
    ) ELSE (
    cmake --build build --target help
    )
  - IF "%GENERATOR%"=="Visual Studio 14 2015" (
    cmake --build build --target INSTALL -- %BUILDFLAGS%
    ) ELSE (
    cmake --build build --target install -- %BUILDFLAGS%
    )
  - IF "%GENERATOR%"=="Visual Studio 14 2015" (
    cmake --build build --target PACKAGE_SOURCE -- %BUILDFLAGS%
    ) ELSE (
    cmake --build build --target package_source -- %BUILDFLAGS%
    )
  - IF "%GENERATOR%"=="Visual Studio 14 2015" (
    cmake --build build --target PACKAGE -- %BUILDFLAGS%
    ) ELSE (
    cmake --build build --target package -- %BUILDFLAGS%
    )

deploy: off
