# See http://msdn.microsoft.com/en-us/library/ms164311.aspx for
# command-line options to MSBuild.

# Speeding up a Visual Studio build.
# http://blogs.msdn.com/b/vcblog/archive/2011/01/05/damn-my-vc-project-is-building-slower-in-vs2010-what-do-i-do-now-a-step-by-step-guide.aspx
version: 'build-{build}-{branch}'

platform: x64

configuration:
  - Release

image:
  - Visual Studio 2017

build:
  parallel: true

environment:
  # Create expected SHELL variable for pipenv.
  SHELL: "windows"
  CTEST_OUTPUT_ON_FAILURE: "1"
  matrix:
    - GENERATOR: "MSYS Makefiles"
      BUILDFLAGS: "VERBOSE=1"
      CMAKEARGS: ""
      TESTING_TARGET: "test"
      PACKAGE_SOURCE: "1"
    - GENERATOR: "Visual Studio 15 2017 Win64"
      BUILDFLAGS: "/verbosity:normal"
      CMAKEARGS: "-DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
      TESTING_TARGET: "RUN_TESTS"
    - GENERATOR: "Ninja"
      BUILDFLAGS: "-v"
      CMAKEARGS: ""
      TESTING_TARGET: "test"
      PACKAGE_SOURCE: "1"

init:
  - set PATH=C:\msys64\MINGW64\bin;C:\msys64\usr\bin;%PATH%
  - set PATH=C:\Python36;C:\Python36\Scripts;%PATH%
  # Remove Python 2.7 from path
  - set PATH=%PATH:C:\Python27;=%
  - set PATH=%PATH:C:\Python27\Scripts;=%

install:
  - '%APPVEYOR_BUILD_FOLDER%\.scripts\install.bat'

before_build:
  - cd c:\projects\message
  - python --version
  - cmake --version

build_script:
  - cmake -H. -Bbuild
          -G"%GENERATOR%"
          -DCMAKE_BUILD_TYPE=%CONFIGURATION%
          -DCMAKE_INSTALL_PREFIX=C:\projects\software\message
          %CMAKEARGS%
  - cmake --build build
          --target install
          --config %CONFIGURATION%
          -- %BUILDFLAGS%
  - cmake --build build
          --target %TESTING_TARGET%
          --config %CONFIGURATION%
  - if "%PACKAGE_SOURCE%"=="1" (
      cmake --build build --target package_source --config %CONFIGURATION% -- %BUILDFLAGS%
    )
  - cmake --build build
          --target package
          --config %CONFIGURATION%
          -- %BUILDFLAGS%

deploy: off
